version: '3.7'
services:
  findr:
    image: andrewsamokhvalov/findr:latest
    env_file:
      - .env
    build: .
    volumes:
      - ./telegram.session:/app/telegram.session
      - ./db.sqlite:/app/db.sqlite
      - ./chroma:/app/chroma