#FROM python:3.9.17-buster as builder
#
#ENV POETRY_NO_INTERACTION=1 \
#    POETRY_VIRTUALENVS_IN_PROJECT=1 \
#    POETRY_VIRTUALENVS_CREATE=1 \
#    POETRY_CACHE_DIR=/tmp/poetry_cache \
#    POETRY_VERSION=1.5.1
#
#RUN pip install "poetry==${POETRY_VERSION}"
#RUN apt-get update && apt-get install -y firefox-esr
#
#WORKDIR /app
#
#COPY poetry.lock pyproject.toml ./
#RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --without dev --no-root
#
#
#FROM python:3.9.17-slim-buster as runtime
#
#ENV VIRTUAL_ENV=/app/.venv \
#    PATH="/app/.venv/bin:$PATH" \
#    PYTHONDONTWRITEBYTECODE=1 \
#    PYTHONUNBUFFERED=1
#
#COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
## TODO: Move firefox
## TODO: Slim don't have sqlite
#COPY src ./src
#
#CMD ["python", "./src/main.py"]